apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: {{.Chart.Name }}-port
    port: {{.Values.service.port }}
    targetPort: {{.Values.service.port }}
    protocol: TCP
  selector:
    app: {{.Chart.Name}}  